name: algorithm_visualizer
description: "This will be something great"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.3.0
  get_it: ^9.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  riverpod: ^2.5.1 # not used yet
  flutter_riverpod: ^2.5.1
  get_storage: ^2.1.1
  animations: ^2.2.0 # not used yet
  collection: ^1.19.1
  async: ^2.13.1
  google_fonts: ^8.2.1
  fl_chart: ^1.2.0

  cupertino_icons: ^1.0.9
  freezed_annotation: ^2.4.1
#  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  very_good_analysis: ^10.3.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
        - asset: assets/fonts/JetBrainsMono.ttf
          weight: 700
  assets:
    - assets/problems.json
#
#flutter_native_splash:
#  android: true
#  ios: true
#  web: false
#
#  # background_image: "assets/background.png"
#  image: "assets/splash_5.png"
#  color: "#ffffff"
#
#  android_12:
#  # branding: "assets/android_branding.png"