name: algorithm_visualizer
description: "This will be something great"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  riverpod: ^2.5.1 # not used yet
  flutter_riverpod: ^2.5.1
  get_storage: ^2.1.1
  animations: ^2.0.11 # not used yet

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
