import 'package:algorithm_visualizer/core/resources/color_manager.dart';
import 'package:flutter/material.dart';

enum ThemeEnum {
  primaryColor,
  focusColor,
  howItWorksColor,
  glassColor,
  columnColor,
  backgroundForSortingColor,
  cardGlassColor,
  shadowColor,
  greyD6Color,
  mainDarkColor,
  white2DarkColor,
  textDarkColor,
  text2DarkColor,
  borderPurpleColor,
  lightPurpleColor,

  whiteD1Color,
  whiteD2Color,
  whiteD3Color,
  whiteD4Color,
  whiteD5Color,
  whiteD7Color,
  whiteColor,
  transparentWhiteColor,
  transparentColor,
  blackColor,
  whiteOp60Color,
  solidWhiteOp60Color,
  whiteOp50Color,
  whiteOp20Color,
  greyColor,
  grey5Color,
  darkGreyColor,
  trendsRankingColor,
  hoverColor,
  blackOp80,
  blackOp50,
  blackOp20,
  blackOp10,
  bottomSheetColor,

  blueColor,
  darkPurpleColor,
  darkBlueColor,
  mediumBlueColor,
  lightBlueColor,
  greenColor,
  redColor,
  orangeColor,
  //
  comparedColor,
}

extension ThemeExtension on BuildContext {
  Map<ThemeEnum, Color> get _colors {
    return {
      ThemeEnum.primaryColor: Theme.of(this).primaryColor,
      ThemeEnum.focusColor: Theme.of(this).focusColor,
      ThemeEnum.glassColor: Theme.of(this).hintColor,
      ThemeEnum.cardGlassColor: ColorManager.cardDarkColor,
      ThemeEnum.shadowColor: Theme.of(this).shadowColor,
      ThemeEnum.howItWorksColor: ColorManager.howItWorksColor,
      ThemeEnum.white2DarkColor: ColorManager.white2DarkColor,
      ThemeEnum.columnColor: ColorManager.columnSortColor,
      ThemeEnum.backgroundForSortingColor: ColorManager.backgroundForSortingColor,
      ThemeEnum.textDarkColor: ColorManager.textDarkColor,
      ThemeEnum.text2DarkColor: ColorManager.text2DarkColor,
      ThemeEnum.lightPurpleColor: ColorManager.lightPurpleColor,
      ThemeEnum.borderPurpleColor: ColorManager.borderPurpleColor,

      /// what ever dark or light. Maybe if we have multiple themes, it will save a lot of time.
      ThemeEnum.whiteD1Color: Theme.of(this).dialogTheme.backgroundColor!,
      ThemeEnum.whiteD2Color: Theme.of(this).primaryColorLight,
      ThemeEnum.bottomSheetColor: Theme.of(this).bottomSheetTheme.backgroundColor ?? Theme.of(this).primaryColorLight,
      ThemeEnum.whiteD3Color: Theme.of(this).textTheme.headlineLarge?.color ?? ColorManager.grey,
      ThemeEnum.whiteD4Color: Theme.of(this).colorScheme.primaryContainer,
      ThemeEnum.whiteD5Color: ColorManager.whiteD5,
      ThemeEnum.whiteD7Color: ColorManager.whiteD7,
      ThemeEnum.transparentColor: ColorManager.transparent,
      ThemeEnum.transparentWhiteColor: ColorManager.whiteOp20,
      ThemeEnum.blackOp20: ColorManager.blackOp20,
      ThemeEnum.trendsRankingColor: ColorManager.rankingGrey,

      ThemeEnum.blackOp10: Theme.of(this).dividerColor,

      ThemeEnum.whiteColor: ColorManager.white,
      ThemeEnum.blackColor: ColorManager.black,
      ThemeEnum.whiteOp60Color: ColorManager.whiteOp60,
      ThemeEnum.solidWhiteOp60Color: ColorManager.whiteOp60,
      ThemeEnum.whiteOp50Color: ColorManager.whiteOp50,
      ThemeEnum.whiteOp20Color: ColorManager.whiteOp20,
      ThemeEnum.blackOp80: ColorManager.blackOp80,
      ThemeEnum.blackOp50: ColorManager.blackOp50,
      ThemeEnum.hoverColor: Theme.of(this).hoverColor,
      ThemeEnum.mainDarkColor: ColorManager.mainDarkColor,

      ThemeEnum.greyColor: ColorManager.grey,
      ThemeEnum.greyD6Color: ColorManager.greyD6,
      ThemeEnum.grey5Color: ColorManager.greyD9,
      ThemeEnum.darkGreyColor: Theme.of(this).textTheme.bodyLarge?.color ?? ColorManager.greyD3,
      ThemeEnum.blueColor: ColorManager.blue,
      ThemeEnum.darkBlueColor: ColorManager.darkBlue,
      ThemeEnum.mediumBlueColor: ColorManager.mediumBlue,
      ThemeEnum.lightBlueColor: ColorManager.finishedSearcherBlue,
      ThemeEnum.greenColor: ColorManager.green,
      ThemeEnum.redColor: ColorManager.red,
      ThemeEnum.orangeColor: ColorManager.orange,
      ThemeEnum.comparedColor: ColorManager.dividerBlue,
      ThemeEnum.darkPurpleColor: ColorManager.darkPurple,
    };
  }

  Color getColor(ThemeEnum color) => _colors[color] ?? Theme.of(this).primaryColor;
}
