// Coverage gate for the test suite. See specs/008-full-app-testing/contracts/coverage-gate-contract.md.
//
//   dart run tool/coverage_gate.dart prepare   writes test/coverage_helper_test.dart
//   dart run tool/coverage_gate.dart check     reads coverage/lcov.info, exits 0 / 1 / 2

import 'dart:convert';
import 'dart:io';

const _configPath = 'tool/coverage_gate.json';
const _helperPath = 'test/coverage_helper_test.dart';

void main(List<String> args) {
  switch (args.firstOrNull) {
    case 'prepare':
      prepare();
    case 'check':
      exit(check());
    default:
      stderr.writeln('Usage: dart run tool/coverage_gate.dart <prepare|check>');
      exit(2);
  }
}

/// Imports every lib file, so a file no test loads still shows up in the report at 0%.
void prepare({String libRoot = 'lib', String configPath = _configPath, String outPath = _helperPath}) {
  final config = jsonDecode(File(configPath).readAsStringSync()) as Map<String, dynamic>;
  final exclude = (config['exclude'] as List).cast<String>().map(_globToRegExp).toList();
  final package = RegExp(r'^name:\s*(\S+)', multiLine: true)
      .firstMatch(File('pubspec.yaml').readAsStringSync())!
      .group(1);

  final files = Directory(libRoot)
      .listSync(recursive: true)
      .whereType<File>()
      .map((file) => file.path.replaceAll(r'\', '/'))
      .where((path) => path.endsWith('.dart') && !path.endsWith('.g.dart'))
      .where((path) => !exclude.any((glob) => glob.hasMatch(path)))
      .where((path) => !File(path).readAsLinesSync().any((line) => line.startsWith('part of')))
      .toList()
    ..sort();

  final out = StringBuffer()
    ..writeln('// Generated by tool/coverage_gate.dart prepare. Do not edit.')
    ..writeln('// ignore_for_file: unused_import')
    ..writeln()
    ..writeln("import 'package:flutter_test/flutter_test.dart';");
  for (var i = 0; i < files.length; i++) {
    out.writeln("import 'package:$package/${files[i].substring(libRoot.length + 1)}' as i$i;");
  }
  out
    ..writeln()
    ..writeln('void main() {')
    ..writeln("  test('coverage helper', () {});")
    ..writeln('}');

  File(outPath).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $outPath (${files.length} files).');
}

/// Returns the exit code: 0 passed, 1 a rule failed, 2 an input is missing.
int check({
  String lcovPath = 'coverage/lcov.info',
  String configPath = _configPath,
  String testRoot = 'test',
  void Function(String)? output,
}) {
  final log = output ?? stdout.writeln;
  final lcovFile = File(lcovPath);
  final configFile = File(configPath);
  if (!lcovFile.existsSync() || !configFile.existsSync()) {
    log('Missing ${!lcovFile.existsSync() ? lcovPath : configPath}.');
    return 2;
  }

  final Map<String, dynamic> config;
  try {
    config = jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  } on FormatException catch (e) {
    log('Unreadable $configPath: ${e.message}');
    return 2;
  }

  final exclude = (config['exclude'] as List).cast<String>().map(_globToRegExp).toList();
  final logicFolders = (config['logicFolders'] as List).cast<String>().toSet();
  final areas = (config['areas'] as Map<String, dynamic>)
      .entries
      .map((entry) => _Area(entry.key, entry.value as Map<String, dynamic>, config))
      .toList();
  // Most specific path first, so the engine wins over the code editor, and that over core.
  final bySpecificPath = [...areas]..sort((a, b) => b.path.length.compareTo(a.path.length));

  final overall = _Lines();
  for (final file in _parseLcov(lcovFile.readAsStringSync())) {
    if (exclude.any((glob) => glob.hasMatch(file.path))) continue;
    final area = bySpecificPath.where((area) => file.path.startsWith(area.path)).firstOrNull;
    if (area == null) continue;

    area.all.add(file);
    overall.add(file);
    if (file.path.split('/').reversed.skip(1).any(logicFolders.contains)) area.logic.add(file);
    if (!_hasTest(file.path, testRoot)) area.untested.add(file.path);
  }

  final failures = <String>[];
  log('area         coverage   logic   no test   gated');
  for (final area in areas) {
    log('${area.name.padRight(12)} ${area.all.percentText.padLeft(8)} ${area.logic.percentText.padLeft(7)} '
        '${area.untested.length.toString().padLeft(9)}   ${area.gated ? 'yes' : 'no'}');
    if (!area.gated) continue;

    for (final path in area.untested) {
      failures.add('R1 ${area.name}: $path has no test');
    }
    if (area.all.percent < area.min) {
      failures.add('R2 ${area.name}: coverage ${area.all.percentText} is below ${area.min}%');
    }
    if (area.logic.found > 0 && area.logic.percent < area.logicMin) {
      failures.add('R3 ${area.name}: logic coverage ${area.logic.percentText} is below ${area.logicMin}%');
    }
  }

  final overallMin = (config['overallMin'] as num).toDouble();
  log('overall      ${overall.percentText.padLeft(8)}');
  if (config['overallGated'] == true && overall.percent < overallMin) {
    failures.add('R4 overall: coverage ${overall.percentText} is below $overallMin%');
  }

  if (failures.isEmpty) return 0;
  log('');
  for (final failure in failures) {
    log(failure);
  }
  return 1;
}

/// `test/<path>_test.dart`, or `test/<path>_<topic>_test.dart` when one file needs several.
bool _hasTest(String libPath, String testRoot) {
  final withoutLib = libPath.substring('lib/'.length, libPath.length - '.dart'.length);
  final slash = withoutLib.lastIndexOf('/');
  final dir = Directory('$testRoot/${withoutLib.substring(0, slash + 1)}');
  final name = withoutLib.substring(slash + 1);
  if (!dir.existsSync()) return false;

  return dir.listSync().whereType<File>().any((file) {
    final base = file.uri.pathSegments.last;
    return base == '${name}_test.dart' || (base.startsWith('${name}_') && base.endsWith('_test.dart'));
  });
}

List<_FileLines> _parseLcov(String lcov) {
  final files = <_FileLines>[];
  _FileLines? current;
  for (final line in const LineSplitter().convert(lcov)) {
    if (line.startsWith('SF:')) {
      final path = line.substring(3).replaceAll(r'\', '/');
      final lib = path.indexOf('lib/');
      current = _FileLines(lib == -1 ? path : path.substring(lib));
    } else if (line.startsWith('DA:') && current != null) {
      current.found++;
      if (int.parse(line.substring(3).split(',')[1]) > 0) current.hit++;
    } else if (line == 'end_of_record' && current != null) {
      files.add(current);
      current = null;
    }
  }
  return files;
}

RegExp _globToRegExp(String glob) {
  final pattern =
      glob.split('**/').map((part) => part.split('*').map(RegExp.escape).join('[^/]*')).join('(.*/)?');
  return RegExp('^$pattern\$');
}

class _FileLines {
  _FileLines(this.path);

  final String path;
  int found = 0;
  int hit = 0;
}

class _Lines {
  int found = 0;
  int hit = 0;

  void add(_FileLines file) {
    found += file.found;
    hit += file.hit;
  }

  double get percent => found == 0 ? 100 : hit * 100 / found;

  String get percentText => found == 0 ? '-' : '${percent.toStringAsFixed(1)}%';
}

class _Area {
  _Area(this.name, Map<String, dynamic> json, Map<String, dynamic> config)
      : path = json['path'] as String,
        gated = json['gated'] as bool,
        min = ((json['min'] ?? config['areaMin']) as num).toDouble(),
        logicMin = ((json['logicMin'] ?? config['logicMin']) as num).toDouble();

  final String name;
  final String path;
  final bool gated;
  final double min;
  final double logicMin;

  final all = _Lines();
  final logic = _Lines();
  final untested = <String>[];
}
