import 'package:algorithm_visualizer/features/practice/helper/problem.dart';

const List<Problem> problems = [
  Problem(
      id: 1,
      num: 1,
      name: 'Two Sum',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 49.3,
      tags: ['Array', 'Hash Table']),
  Problem(
      id: 2,
      num: 2,
      name: 'Add Two Numbers',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.attempted,
      acceptance: 38.2,
      tags: ['Linked List', 'Math']),
  Problem(
      id: 3,
      num: 3,
      name: 'Longest Substring Without Repeating Chars',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.solved,
      acceptance: 33.8,
      tags: ['String', 'Sliding Window']),
  Problem(
      id: 4,
      num: 4,
      name: 'Median of Two Sorted Arrays',
      difficulty: ProblemDifficulty.hard,
      status: ProblemStatus.todo,
      acceptance: 35.1,
      tags: ['Array', 'Binary Search']),
  Problem(
      id: 5,
      num: 5,
      name: 'Longest Palindromic Substring',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.solved,
      acceptance: 32.4,
      tags: ['String', 'DP']),
  Problem(
    id: 9,
    num: 9,
    name: 'Palindrome Number',
    difficulty: ProblemDifficulty.easy,
    status: ProblemStatus.solved,
    acceptance: 52.8,
    tags: ['Math'],
  ),
  Problem(
      id: 10,
      num: 10,
      name: 'Regular Expression Matching',
      difficulty: ProblemDifficulty.hard,
      status: ProblemStatus.todo,
      acceptance: 28.1,
      tags: ['String', 'DP', 'Recursion']),
  Problem(
      id: 11,
      num: 11,
      name: 'Container With Most Water',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.attempted,
      acceptance: 54.3,
      tags: ['Array', 'Two Pointers']),
  Problem(
      id: 14,
      num: 14,
      name: 'Longest Common Prefix',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.solved,
      acceptance: 41.5,
      tags: ['String', 'Trie']),
  Problem(
      id: 15,
      num: 15,
      name: '3Sum',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.solved,
      acceptance: 31.2,
      tags: ['Array', 'Two Pointers', 'Sorting']),
  Problem(
      id: 20,
      num: 20,
      name: 'Valid Parentheses',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 40.3,
      tags: ['String', 'Stack']),
  Problem(
      id: 21,
      num: 21,
      name: 'Merge Two Sorted Lists',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 62.4,
      tags: ['Linked List', 'Recursion']),
  Problem(
      id: 22,
      num: 22,
      name: 'Generate Parentheses',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.todo,
      acceptance: 74.2,
      tags: ['String', 'Backtracking']),
  Problem(
      id: 23,
      num: 23,
      name: 'Merge k Sorted Lists',
      difficulty: ProblemDifficulty.hard,
      status: ProblemStatus.attempted,
      acceptance: 50.5,
      tags: ['Linked List', 'Heap']),
  Problem(
      id: 33,
      num: 33,
      name: 'Search in Rotated Sorted Array',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.todo,
      acceptance: 39.8,
      tags: ['Array', 'Binary Search']),
  Problem(
      id: 42,
      num: 42,
      name: 'Trapping Rain Water',
      difficulty: ProblemDifficulty.hard,
      status: ProblemStatus.todo,
      acceptance: 60.4,
      tags: ['Array', 'Stack', 'DP']),
  Problem(
      id: 53,
      num: 53,
      name: 'Maximum Subarray',
      difficulty: ProblemDifficulty.medium,
      status: ProblemStatus.solved,
      acceptance: 50.1,
      tags: ['Array', 'DP']),
  Problem(
      id: 70,
      num: 70,
      name: 'Climbing Stairs',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 52.3,
      tags: ['Math', 'DP', 'Memoization']),
  Problem(
      id: 104,
      num: 104,
      name: 'Maximum Depth of Binary Tree',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 74.5,
      tags: ['Tree', 'DFS', 'BFS']),
  Problem(
      id: 206,
      num: 206,
      name: 'Reverse Linked List',
      difficulty: ProblemDifficulty.easy,
      status: ProblemStatus.solved,
      acceptance: 74.9,
      tags: ['Linked List', 'Recursion']),
];
